import { StyleSheet, Platform } from 'react-native';
import { Colors } from '../../constants/colors';
import { Typography } from '../../constants/typography';

export const AUTH_SCREEN_PAD = 28;
export const AUTH_SECTION_AFTER_HEADER = 28;
export const AUTH_GAP_CARD_TO_PRIMARY = 28;
export const AUTH_GAP_BUTTONS = 16;
export const AUTH_GAP_LINK = 28;

export const authStyles = StyleSheet.create({
  screenPad: { paddingHorizontal: AUTH_SCREEN_PAD },
  navBackLabel: {
    ...Typography.body,
    fontSize: 16,
    color: Colors.primaryDark,
    fontWeight: '600',
    marginLeft: 4,
  },
  navBackLabelOnDark: {
    ...Typography.body,
    fontSize: 16,
    color: 'rgba(255,255,255,0.92)',
    fontWeight: '600',
    marginLeft: 4,
  },
  screenTitle: {
    ...Typography.h1,
    fontSize: 28,
    fontWeight: '700',
    color: '#0c1222',
    marginBottom: 10,
    letterSpacing: -0.4,
  },
  screenSubtitle: {
    ...Typography.body,
    fontSize: 16,
    lineHeight: 24,
    color: '#334155',
    marginBottom: AUTH_SECTION_AFTER_HEADER,
    maxWidth: 360,
  },
  screenTitleLogin: {
    ...Typography.h1,
    fontSize: 28,
    fontWeight: '700',
    color: '#ffffff',
    marginBottom: 10,
    letterSpacing: -0.4,
  },
  screenSubtitleLogin: {
    ...Typography.body,
    fontSize: 16,
    lineHeight: 24,
    color: 'rgba(255,255,255,0.82)',
    marginBottom: AUTH_SECTION_AFTER_HEADER,
    maxWidth: 360,
  },
  heroWrap: {
    alignItems: 'center',
    marginBottom: 20,
  },
  heroLogoWrap: {
    width: 148,
    height: 148,
    marginBottom: 24,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9999,
    overflow: 'hidden',
  },
  heroLogo: {
    width: '100%',
    height: '100%',
  },
  brandTitle: {
    ...Typography.h1,
    fontSize: 38,
    fontWeight: '700',
    letterSpacing: -0.8,
    color: '#0f172a',
    textAlign: 'center',
    marginTop: 2,
  },
  tagline: {
    ...Typography.body,
    fontSize: 16,
    color: '#1e293b',
    textAlign: 'center',
    lineHeight: 24,
    marginTop: 14,
    paddingHorizontal: 12,
    maxWidth: 340,
    alignSelf: 'center',
    fontWeight: '500',
  },
  taglineWelcome: {
    marginBottom: 4,
  },
  pill: {
    alignSelf: 'center',
    marginTop: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 24,
    backgroundColor: 'rgba(255,255,255,0.5)',
  },
  pillText: {
    ...Typography.caption,
    fontSize: 12,
    color: Colors.primaryDark,
    fontWeight: '700',
    letterSpacing: 0.6,
  },
  nameRow: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  nameField: {
    flex: 1,
  },
  nameFieldSpacer: {
    marginRight: 12,
  },
  authForm: {
    marginBottom: 4,
  },
  primaryBtn: {
    borderRadius: 999,
    overflow: 'hidden',
    marginTop: AUTH_GAP_CARD_TO_PRIMARY,
    minHeight: 54,
    ...Platform.select({
      ios: {
        shadowColor: Colors.primaryDark,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.38,
        shadowRadius: 14,
      },
      android: { elevation: 10 },
    }),
  },
  btnGrad: {
    paddingVertical: 17,
    minHeight: 54,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  primaryText: {
    ...Typography.bodyBold,
    fontSize: 17,
    color: Colors.white,
    letterSpacing: 0.2,
  },
  secondaryBtn: {
    borderRadius: 999,
    borderWidth: 2,
    borderColor: 'rgba(42, 64, 82, 0.45)',
    backgroundColor: 'rgba(255,255,255,0.72)',
    paddingVertical: 16,
    minHeight: 54,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: AUTH_GAP_BUTTONS,
    ...Platform.select({
      ios: {
        shadowColor: '#0f172a',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
      },
      android: { elevation: 3 },
    }),
  },
  secondaryText: {
    ...Typography.bodyBold,
    color: Colors.primaryDark,
    fontSize: 16,
    letterSpacing: 0.2,
  },
  secondaryBtnWelcome: {
    borderRadius: 999,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.42)',
    backgroundColor: 'rgba(255,255,255,0.1)',
    paddingVertical: 16,
    minHeight: 54,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: AUTH_GAP_BUTTONS,
    ...Platform.select({
      ios: {
        shadowColor: '#0f172a',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.12,
        shadowRadius: 12,
      },
      android: { elevation: 3 },
    }),
  },
  secondaryTextWelcome: {
    ...Typography.bodyBold,
    color: 'rgba(255,255,255,0.92)',
    fontSize: 16,
    letterSpacing: 0.2,
  },
  footerNoteWelcome: {
    ...Typography.caption,
    fontSize: 12,
    lineHeight: 18,
    color: 'rgba(255,255,255,0.62)',
    textAlign: 'center',
    marginTop: 20,
    paddingHorizontal: 8,
  },
  link: {
    marginTop: AUTH_GAP_LINK,
    alignItems: 'center',
    paddingVertical: 10,
  },
  linkText: {
    ...Typography.body,
    fontSize: 15,
    lineHeight: 22,
    color: '#475569',
    textAlign: 'center',
  },
  linkBold: {
    ...Typography.bodyBold,
    fontSize: 15,
    color: Colors.primary,
  },
  linkTextSignUp: {
    ...Typography.body,
    fontSize: 15,
    lineHeight: 22,
    color: 'rgba(255,255,255,0.78)',
    textAlign: 'center',
  },
  linkBoldSignUp: {
    ...Typography.bodyBold,
    fontSize: 15,
    color: '#a8c4d4',
  },
  footerNote: {
    ...Typography.caption,
    fontSize: 12,
    lineHeight: 18,
    color: '#475569',
    textAlign: 'center',
    marginTop: 20,
    paddingHorizontal: 8,
  },
  dividerLine: {
    height: 4,
    width: 56,
    borderRadius: 4,
    backgroundColor: Colors.primary,
    alignSelf: 'center',
    marginBottom: 22,
    opacity: 0.9,
  },
  welcomeActions: {
    paddingTop: 8,
    paddingBottom: 8,
  },
});
